CREATE TABLE IF NOT EXISTS Device_type (
    ID INTEGER PRIMARY KEY
);

ALTER TABLE Device_type ADD COLUMN type TEXT NOT NULL UNIQUE;

INSERT INTO Device_type (type)
SELECT 'my' WHERE NOT EXISTS (SELECT 1 FROM Device_type WHERE type='my');

INSERT INTO Device_type (type)
SELECT 'other' WHERE NOT EXISTS (SELECT 1 FROM Device_type WHERE type='other');

CREATE TABLE IF NOT EXISTS Device (
    ID INTEGER PRIMARY KEY
);

ALTER TABLE Device ADD COLUMN ip TEXT NOT NULL UNIQUE;
ALTER TABLE Device ADD COLUMN type INTEGER NOT NULL;
ALTER TABLE Device ADD COLUMN name TEXT NOT NULL UNIQUE;
ALTER TABLE Device ADD COLUMN muted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Device ADD COLUMN blocked INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS Device_new (
    ID INTEGER PRIMARY KEY,
    ip TEXT NOT NULL UNIQUE,
    type INTEGER NOT NULL,
    name TEXT NOT NULL UNIQUE,
    muted INTEGER NOT NULL DEFAULT 0,
    blocked INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY(type) REFERENCES Device_type(ID)
);

INSERT INTO Device_new
SELECT ID, ip, type, name, muted, blocked FROM Device;

DROP TABLE Device;
ALTER TABLE Device_new RENAME TO Device;

CREATE TABLE IF NOT EXISTS Message_type (
    ID INTEGER PRIMARY KEY
);

ALTER TABLE Message_type ADD COLUMN type TEXT NOT NULL UNIQUE;

INSERT INTO Message_type (type)
SELECT 'message' WHERE NOT EXISTS (SELECT 1 FROM Message_type WHERE type='message');

INSERT INTO Message_type (type)
SELECT 'file' WHERE NOT EXISTS (SELECT 1 FROM Message_type WHERE type='file');

CREATE TABLE IF NOT EXISTS Message (
    ID INTEGER PRIMARY KEY
);

ALTER TABLE Message ADD COLUMN sender INTEGER NOT NULL;
ALTER TABLE Message ADD COLUMN addressee INTEGER NOT NULL;
ALTER TABLE Message ADD COLUMN message_type INTEGER NOT NULL;
ALTER TABLE Message ADD COLUMN text TEXT NOT NULL;
ALTER TABLE Message ADD COLUMN date TEXT NOT NULL;
ALTER TABLE Message ADD COLUMN viewed INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS Message_new (
    ID INTEGER PRIMARY KEY,
    sender INTEGER NOT NULL,
    addressee INTEGER NOT NULL,
    message_type INTEGER NOT NULL,
    text TEXT NOT NULL,
    date TEXT NOT NULL,
    viewed INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY(sender) REFERENCES Device(ID),
    FOREIGN KEY(addressee) REFERENCES Device(ID),
    FOREIGN KEY(message_type) REFERENCES Message_type(ID)
);

INSERT INTO Message_new
SELECT ID, sender, addressee, message_type, text, date, viewed FROM Message;

DROP TABLE Message;
ALTER TABLE Message_new RENAME TO Message;
